# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7c9ae46d-3abb-497e-b399-f117c3e7e93a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7c9ae46d-3abb-497e-b399-f117c3e7e93a".device = "/dev/disk/by-uuid/7c9ae46d-3abb-497e-b399-f117c3e7e93a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1596-D22A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-1b44a119-b154-42d6-bcdc-4afdde248566"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
